float16 leftFrontFoot
float16 leftFrontThigh
float16 leftBackFoot
float16 leftBackThigh
float16 rightFrontFoot
float16 rightFrontThigh
float16 rightBackFoot
float16 rightBackThigh
---
bool result
---
bool partial_result
