float32 left_front_foot
float32 left_front_thigh
float32 left_back_foot
float32 left_back_thigh
float32 right_front_foot
float32 right_front_thigh
float32 right_back_foot
float32 right_back_thigh
---
bool result
---
bool partial_result